<?php

$queryTransacciones ="  SELECT	p.codigo, p.descripcion, ge.cantidad
                        FROM	producto p
                                INNER JOIN generacion_etiquetas ge ON ge.codigo_origen = p.codigo";

$transacciones = $this->db->queryToArray(sprintf($queryTransacciones));

$generator = new BarcodeGeneratorHTML();

$total = 0;
foreach ($transacciones as $trx) {
    $total += $trx['cantidad'];
}

?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title></title>
    <style>
        body {
            width: 19cm;
            font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
            font-size: 10px;
        }
        label {
            display: block;
            text-align: center;
            max-width: 200px;
            word-wrap: break-word
        }
        div {
            margin: auto;
        }
    </style>
</head>
<body>
<table>
    <?php
        reset($transacciones);
        $p = current($transacciones);
        $conteo = 0;
        $cantidad = (int)$p['cantidad'];
    ?>
    <?php for($i = 1; $i <= $total; $i++){
        if($conteo == $cantidad){
            $p = next($transacciones);
            $cantidad = (int)$p['cantidad'];
            $conteo = 0;
        }else
            $conteo++;
    ?>
        <?php if ($i%3 == 1) echo "<tr>" ?>
            <td style="padding-left:5px; width: 198px;">
                <div style="height: 90px;">
                    <label><?php echo $p['descripcion'] ?></label>
                    <label><?php echo $generator->getBarcode($p['codigo'], $generator::TYPE_CODE_128); ?></label>
                    <label><?php echo $p['codigo'] ?></label>
                </div>
            </td>
        <?php if ($i%3 == 0) echo "</tr>" ?>
    <?php } ?>
</table>
</body>
</html>