<?php

if ($tipoGeneracion == 0) {
    $queryTransacciones = "  SELECT	p.codigo_origen, p.descripcion, ge.cantidad as haber
                             FROM	producto p
                             INNER JOIN generacion_etiquetas ge ON ge.codigo_origen = p.codigo_origen ";

    $transacciones = $this->db->queryToArray($queryTransacciones);
} else {

    $queryTransacciones = "  SELECT	p.codigo_origen, p.descripcion, t.haber
                             FROM	trx_transacciones t
                             INNER JOIN producto p ON p.id_producto = t.id_producto ";

    $where = " WHERE 1 = 1 ";

    if ($idSucursal != "")
        $where .= " AND t.id_sucursal = " . $idSucursal;

    if ($idTipo != "")
        $where .= " AND p.id_tipo = " . $idTipo;

    $transacciones = $this->db->queryToArray($queryTransacciones . $where);

}

$generator = new BarcodeGeneratorHTML();

$total = 0;
foreach ($transacciones as $trx) {
    $total += $trx['haber'];
}

?>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title></title>
    <style>
        body {
            width: 19cm;
            font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
            font-size: 10px;
        }
        label {
            display: block;
            text-align: center;
            max-width: 200px;
            word-wrap: break-word
        }
        div {
            margin: auto;
        }
    </style>
</head>
<body>
<table border="0">
    <?php
    reset($transacciones);
    $p = current($transacciones);
    $conteo = 0;
    $cantidad = (int)$p['haber'];
    ?>
    <?php for($i = 1; $i <= $total; $i++){
        if($conteo == $cantidad){
            $p = next($transacciones);
            $cantidad = (int)$p['haber'];
            $conteo = 0;
        }else
            $conteo++;
        ?>
        <?php if ($i%3 == 1) echo "<tr>" ?>
        <td style="padding-left:5px; width: 198px;">
            <div style="height: 90px;">
                <label><?php echo $p['descripcion'] ?></label>
                <label><?php echo $generator->getBarcode($p['codigo_origen'], $generator::TYPE_CODE_128); ?></label>
                <label><?php echo $p['codigo_origen'] ?></label>
            </div>
        </td>
        <?php if ($i%3 == 0) echo "</tr>" ?>
    <?php } ?>
</table>
</body>
</html>