<?php
$queryVenta = " SELECT 	v.usuario_venta, v.id_venta, v.total, v.fecha_creacion, CONCAT(c.nombres,' ',c.apellidos) nombre_cliente, IFNULL(c.factura_nit, 'C/F') factura_nit, IFNULL(c.factura_nombre, 'C/F') factura_nombre, IFNULL(c.factura_direccion, ' ') factura_direccion, COUNT(vd.id_venta_detalle) cant_productos
                FROM 	trx_venta v
                LEFT JOIN 	clientes c ON c.id_cliente=v.id_cliente
                LEFT JOIN	trx_venta_detalle vd ON vd.id_venta = v.id_venta
                WHERE   v.id_venta=%s";

$venta = $this->db->queryToArray(sprintf($queryVenta, $ventaId));
$venta = sanitize_by_keys($venta[0], ['nombre_cliente']);

$queryProductos = " SELECT	tp.id_venta_detalle, p.id_tipo, p.id_producto, m.id_tipo, tp.cantidad, CONCAT(m.nombre, ' - ', p.nombre) as descripcion, tp.precio_venta as precio_unitario, p.precio_venta as precio_sugerido, p.codigo codigo_origen
                    FROM 	trx_venta_detalle tp
                    LEFT JOIN 	producto p ON p.id_producto = tp.id_producto
                    LEFT JOIN 	tipo m ON m.id_tipo = p.id_tipo
                    WHERE   id_venta=%s
                    AND		tp.cantidad > 0";

$productos = $this->db->queryToArray(sprintf($queryProductos, $ventaId));
$productos = sanitize_array_by_keys($productos, ['descripcion']);

$total = 0;
$descuento = 0;
$subtotal = 0;
?>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        <style>
            body {
                width: 19cm;
                font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
                font-size: 13px;
            }
            td {
                text-align: center;
            }
            .text-left {
                min-height: 17px;
                width: 48%;
                text-align: left;
                display: inline-block;
            }
            .text-right {
                min-height: 17px;
                width: 45%;
                text-align: right;
                display: inline-block;
            }
        </style>
    </head>
    <body>
        <table style="width: 90%; margin:20px auto 0px auto;background-color: #fff" border="0">
            <tr>
                <th style='font-size: 21px; text-align: center' colspan="2"><center>ALLURING CONCEPT</center></th>
            </tr>
            <tr>
                <th style='width: 20%; text-align: left'>Número</th>
                <td style='text-align: left'><?php echo $venta['id_venta'] ?></td>
            </tr>
            <tr>
                <th style='width: 20%; text-align: left'>Empleado</th>
                <td style='text-align: left'><?php echo $venta['usuario_venta'] ?></td>
            </tr>
            <tr>
                <th style='text-align: left'>Fecha</th>
                <td style='text-align: left'><?php echo DateTime::createFromFormat(SQL_DT_FORMAT, $venta['fecha_creacion'])->format(SHOW_DT_FORMAT) ?></td>
            </tr>
            <tr>
                <th style='text-align: left'>Nombre</th>
                <td style='text-align: left'><?php echo $venta["factura_nit"] ?></td>
            </tr>
            <tr>
                <th style='text-align: left'>NIT</th>
                <td style='text-align: left'><?php echo $venta["factura_nombre"] ?></td>
            </tr>
            <tr>
                <th style='text-align: left'>Dirección</th>
                <td style='text-align: left'><?php echo $venta["factura_direccion"] ?></td>
            </tr>
            <tr>
                <th style='text-align: left'>Productos</th>
                <td style='text-align: left'><?php echo $venta["cant_productos"] ?></td>
            </tr>
        </table>
        <table style="width: 90%; margin:20px auto 0px auto;background-color: #fff" border="1">
            <tr>
                <th style='width: 10%'>Producto</th>
                <th style='width: 65%'>Descripción</th>
                <th style='width: 10%'>Cantidad</th>
                <th style='width: 25%'>Precio Unitario</th>
                <th style='width: 25%'>Precio Sugerido</th>
                <th style='width: 25%'>Precio Total</th>
            </tr>
            <?php 
            foreach($productos as $p){
                ?>
            <tr>
                <td valign="top"><?php echo $p['codigo_origen'] ?></td>
                <td style="font-size: 12px"> <?php echo $p['descripcion']; ?> </td>
                <td valign="top"><?php echo $p['cantidad'] ?></td>
                <td valign="top" > <?php echo number_format($p['precio_unitario'], 2); ?> </td>
                <td valign="top" > <?php echo number_format($p['precio_sugerido'], 2); ?> </td>
                <td valign="top"> <?php echo number_format(($p['precio_unitario'] * $p['cantidad']), 2); ?> </td>
            </tr>
                <?php
                $total += ($p['precio_unitario'] * $p['cantidad']);
                $subtotal += ($p['precio_sugerido'] * $p['cantidad']);
            }
            ?>
        </table>
        <table style="width: 90%; margin:20px auto 0px auto;background-color: #fff" border="0">
            <tr>
                <th style='text-align: right'>TOTAL VENTA</th>
                <th style='width: 18%'><?php echo number_format($total, 2) ?></th>
            </tr>
        </table>
    </body>
</html>


