<div class='col-md-12 col-lg-12' ng-controller="ModuleCtrl">
    <div class="well well-sm row" style="padding-bottom: 0px" ng-show='noMode'>
        <div class="form-group col-md-8 col-lg-8 col-sm-6 col-xs-12">
            <label style="display: inline-block">Ordenar por:</label>
            <select style="max-width: 50%; display: inline-block" ng-model="sortBy" class="form-control input-sm">
                <option value="">-- Seleccione --</option>
                <option ng-repeat="col in gridCols" value="{{col.VALOR}}">{{col.LABEL}}</option>
            </select>
        </div>
    </div>

    <div class='table-responsive'>
        <table class='table table-striped table-bordered' ng-show='noMode'>
            <tr>
                <th ng-repeat='col in gridCols' ng-bind='col.LABEL'></th>
                <td>&nbsp;</td> 
            </tr>
            <tr>
                <?php
                foreach ($this->gridCols as $key => $value) {
                    ?>
                    <td><input type='text' ng-model='search.<?php echo $value ?>'/></td>
                <?php
                }
                ?>
                <td>&nbsp;</td>
            </tr>
            <tr ng-class="{info:row.selected}" ng-click='selectRow(row)' ng-repeat='row in filteredRows'>
                <td ng-repeat='col in gridCols' ng-bind='row[col.VALOR]'></td>
                <td>
                    <img bn-lazy-src="media/uploads/{{row.imagen}}?rand={{rand}}" alt="{{lastSelected.codigo}}" class="img-thumbnail w-75">
                </td>
            </tr>
        </table>
    </div>
    <form ng-show='editMode||newMode' class='col-md-12 col-lg-12' id="mantForm" name="mantForm" method="post">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <input ng-model="lastSelected.id_producto" type="hidden" class='form-control'/>
                <div class='form-group form-group-sm'>
                    <label for='codigo' class='control-label'>Código</label>
                    <input readonly ng-model="lastSelected.codigo" type="text" required class='form-control' name='codigo' placeholder='' />
                </div>
                <div class='form-group form-group-sm'>
                    <label for='codigo_origen' class='control-label'>Código Origen</label>
                    <input ng-readonly="editMode" ng-model="lastSelected.codigo_origen" type="text" required class='form-control' name='codigo_origen' placeholder='' />
                </div>
                <div class='form-group form-group-sm'>
                    <label for='nombre' class='control-label'>Nombre</label>
                    <input ng-model="lastSelected.nombre" type="text" required class='form-control' name='nombre' placeholder='' ng-readonly='(editMode&&false)||(newMode&&false)' />
                </div>
                <div class='form-group form-group-sm'>
                    <label for='descripcion' class='control-label'>Descripción</label>
                    <input ng-model="lastSelected.descripcion" type="text" required class='form-control' name='descripcion' placeholder='' ng-readonly='(editMode&&false)||(newMode&&false)' />
                </div>
                <div class='form-group form-group-sm'>
                    <label for='id_tipo' class='control-label'>Categoría</label>
                    <select name="id_tipo" id="id_tipo" ng-model="lastSelected.id_tipo" type="select" required class='form-control'>
                        <option ng-repeat="categoria in categorias" value="{{categoria.id_tipo}}">{{categoria.nombre}}</option>
                    </select>
                </div>
                <div class='form-group form-group-sm'>
                    <label for='precio_venta' class='control-label'>Precio Venta</label>
                    <input ng-model="lastSelected.precio_venta" type="text" required class='form-control' name='precio_venta' placeholder='' ng-readonly='(editMode&&false)||(newMode&&false)'/>
                </div>
                <div class='form-group form-group-sm'>
                    <label for='costo' class='control-label'>Costo</label>
                    <input ng-model="lastSelected.costo" type="text" required class='form-control' name='costo' placeholder='' />
                </div>
                <div class='form-group form-group-sm'>
                    <label for='imagen' class='control-label'>Imagen</label>
                    <input type="file" accept="image/jpeg"  value="lastSelected.imagen" name="file" onchange="angular.element(this).scope().uploadFile(this.files)"/>
                    <input ng-model="lastSelected.imagen" type="hidden" class='form-control'/>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" ng-show="lastSelected.imagen">
                <figure class="figure">
                    <img ng-src="media/uploads/{{lastSelected.imagen}}?rand={{rand}}" alt="{{lastSelected.descripcion}}" class="img-thumbnail">
                    <figcaption class="figure-caption">
                        {{lastSelected.imagen}}
                    </figcaption>
                </figure>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" ng-show="!lastSelected.imagen">
                <figure class="figure">
                    Cargando imagen...
                </figure>
            </div>
        </div>
        <div class="row" style="margin-top: 35px;">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class='form-group'>
                    <div class='btn-group' role='group'>
                        <button class='btn btn-success' title="Guardar" ng-click='finalizar()' type="button" ng-if="newMode">
                            <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Guardar
                        </button>
                        <button class='btn btn-success' title="Guardar" ng-click='finalizarEditado()' type="button" ng-if="editMode">
                            <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Guardar
                        </button>
                        <button class='btn btn-success' title="Guardar" ng-click='finalizarEditadoYCont()' type="button" ng-if="editMode">
                            <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Guardar y continuar
                        </button>
                        <?php
                        if(!$this->onlyEdit){
                            ?>
                            <button class='btn btn-danger' title="Eliminar" ng-click='doDelete()' ng-if="editMode" type="button">
                                <span class='glyphicon glyphicon-trash'></span>&nbsp;Eliminar
                            </button>
                        <?php
                        }
                        ?>
                    </div>
                    <div class='btn-group' role='group'>
                        <button class='btn btn-primary' title="Anterior" ng-click='prev()'  type="button" ng-if="editMode">
                            <span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Anterior
                        </button>
                        <button class='btn btn-primary' title="Siguiente" ng-click='next()'  type="button" ng-if="editMode">
                            Siguiente&nbsp;<span class='glyphicon glyphicon-chevron-right'></span>
                        </button>
                    </div>
                    <button class='btn btn-info' title="Cancelar" ng-click='cancelar()'  type="button">
                        <span class='glyphicon glyphicon-remove'></span>&nbsp;Cancelar
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>