<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-controller="ModuleCtrl" style="margin-bottom: 20px;">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
        <div class="modal fade" id="formaDePagoCat">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Finalizar cambio</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" ng-show="diferencia<=0">
                            <h4>Seguro que desea concluir este cambio?. </h4>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" ng-show="diferencia>0">
                            <h4>Pendiente: Q <span ng-bind="diferencia"></span></h4>
                            <form>
                                <div class="form-group">
                                    <label>Efectivo</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.efectivo" id="efectivo" />
                                </div>
                                <div class="form-group">
                                    <label>Tarjeta</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.tarjeta" />
                                </div>
                                <div class="form-group">
                                    <label>Cheque</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.cheque" />
                                </div>
                                <div ng-show="formaDePago.cheque>0">
                                    <div class="form-group">
                                        <label>Número de cheque</label>
                                        <input type="text" class="not-empty form-control" ng-model="formaDePago.numero_cheque" />
                                    </div>
                                    <div class="form-group">
                                        <label>Banco del cheque</label>
                                        <select class="form-control" ng-model="formaDePago.id_banco">
                                            <option value=''>-- Selecciona uno --</option>
                                            <option value="{{b.id_banco}}" ng-repeat="b in bancos">{{b.nombre}}</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Depósito/Transferencia</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.deposito" />
                                </div>
                                <div ng-show="formaDePago.deposito>0">
                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text" class="form-control" ng-model="formaDePago.numero_deposito" />
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" ng-click="finalizar()">
                        <span class="glyphicon glyphicon-floppy-saved" ></span>&nbsp;Finalizar
                    </button>
                    <button class="btn btn-danger" data-dismiss='modal' type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
        <div class="table-responsive" style="height: 350px; overflow-y: auto" ng-show="aDevolver&&!aEntregar">
            <h3>Seleccione el producto a devolver</h3>
            <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td colspan="9">
                        Buscar: <input id="filterProductos1" type="text" ng-model="filterProductos1"/>
                    </td>
                </tr>
                <tr>
                    <th>Código producto</th>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Tipo / Subtipo</th>
                    <th>Descripción</th>
                    <th>SKU</th>
                    <th>Sucursal</th>
                    <th>Inventario</th>
                    <th>&nbsp;</th>
                </tr>
                <tr ng-repeat="p in productosDev | filter: filterProductos1">
                    <td style="width: 15%;" ng-bind="p.codigo_producto"></td>
                    <td style="width: 15%;" ng-bind="p.nombre"></td>
                    <td style="width: 10%;" ng-bind="p.marca_label"></td>
                    <td style="width: 15%;" >{{p.tipo_label + " - " + p.subtipo_label}}</td>
                    <td style="width: 15%;" ng-bind="p.descripcion"></td>
                    <td style="width: 15%;" ng-bind="p.sku"></td>
                    <td class="be-bold" style="width: 5%; font-size: 15px;" ng-bind="p.stock" ng-class="{'text-success':p.stock>0,'text-danger':p.stock<=0}"></td>
                    <td class="be-bold" style="width: 5%; font-size: 15px;" ng-bind="p.stock_global" ng-class="{'text-success':p.stock_global>0,'text-danger':p.stock_global<=0}"></td>
                    <td style="width: 5%;">
                        <button class="btn btn-success btn-sm" ng-click="addProductoDevolver(p)">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                        </button>
                    </td>
                </tr>
            </table>
        </div>
        <div class="table-responsive" style="height: 200px; overflow-y: auto" ng-show="!aDevolver&&aEntregar">
            <h3>Seleccione el producto a entregar</h3>
            <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <td colspan="9">
                        Buscar: <input id="filterProductos2" type="text" ng-model="filterProductos2"/>
                    </td>
                </tr>
                <tr>
                    <th>Código producto</th>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Tipo / Subtipo</th>
                    <th>Descripción</th>
                    <th>SKU</th>
                    <th>Sucursal</th>
                    <th>Inventario</th>
                    <th>&nbsp;</th>
                </tr>
                <tr ng-repeat="p in productosEnt | filter: filterProductos2">
                    <td style="width: 15%;" ng-bind="p.codigo_producto"></td>
                    <td style="width: 15%;" ng-bind="p.nombre"></td>
                    <td style="width: 10%;" ng-bind="p.marca_label"></td>
                    <td style="width: 15%;" >{{p.tipo_label + " - " + p.subtipo_label}}</td>
                    <td style="width: 15%;" ng-bind="p.descripcion"></td>
                    <td style="width: 15%;" ng-bind="p.sku"></td>
                    <td class="be-bold" style="width: 5%; font-size: 15px;" ng-bind="p.stock" ng-class="{'text-success':p.stock>0,'text-danger':p.stock<=0}"></td>
                    <td class="be-bold" style="width: 5%; font-size: 15px;" ng-bind="p.stock_global" ng-class="{'text-success':p.stock_global>0,'text-danger':p.stock_global<=0}"></td>
                    <td style="width: 5%;">
                        <button class="btn btn-success btn-sm" ng-click="addProductoEntregar(p)">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                        </button>
                    </td>
                </tr>
            </table>
        </div>
        <div class="table-responsive" style="margin-top: 15px" ng-show='productoDevuelto.id_producto||productoEntregado.id_producto'>
            <table class='table table-bordered table-striped'>
                <tr>
                    <td colspan='3'>
                        Resumen <button class='btn btn-sm btn-primary' ng-click='reseteaOperacion()'>Cambiar productos</button>
                    </td>
                </tr>
                <tr>
                    <th>Tipo</th>
                    <th>Nombre</th>
                    <th>Precio Actual</th>
                </tr>
                <tr>
                    <td>A devolver</td>
                    <td ng-bind='productoDevuelto.nombre'></td>
                    <td ng-bind='productoDevuelto.precioFinal'></td>
                </tr>
                <tr>
                    <td>A entregar</td>
                    <td ng-bind='productoEntregado.nombre'></td>
                    <td ng-bind='productoEntregado.precioFinal'></td>
                </tr>
                <tr>
                    <th colspan='3'>Diferencia <span ng-bind='diferencia'></span></th>
                </tr>
            </table>
            <button class="btn btn-success" ng-show="productoDevuelto.id_producto&&productoEntregado.id_producto" ng-click="preparaModoPago()">Continuar</button>
        </div>
    </div>
</div>
