<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-controller="ModuleCtrl" style="margin-bottom: 20px;">
    <div class="modal fade" id="finModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Finalizar ingreso</h4>
                    </div>
                    <div class="modal-body">
                        <label class="control-label">Comentario del ingreso:</label>
                        <textarea ng-model="comentario" class="form-control"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        <button class="btn btn-success" ng-click="finalizar()" ng-if="comentario!=''">Finalizar</button>
                    </div>
                </div>
            </div>
        </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-show="inList">
        <h3 class="text-bold">Proyectos activos</h3>
    </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-show="!inList&&proyectoSel">
        <h3>Ingresar avance</h3>
        
        <h3>Avances actuales</h3>
    </div>
</div>

