<div class='col-md-12 col-lg-12' ng-controller="ModuleCtrl">
    <form class='col-md-12 col-lg-12' id="mantForm" name="mantForm" method="post">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            </div>
        </div>
        <div class="row" style="margin-top: 35px;">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <input ng-model="lastSelected.identificador_excel" type="hidden" class='form-control'/>
                <div class='form-group form-group-sm'>
                    <label for='file' class='control-label'>Archivo Excel</label>
                    <input ng-model="lastSelected.file" type="file" name="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"  value="lastSelected.file" onchange="angular.element(this).scope().uploadFile(this.files)"/>
                    <input ng-model="lastSelected.file" type="hidden" class='form-control'/>
                </div>
            </div>
        </div>
        <div id="loading">
            <img src="media/img/ajax-loader.gif" class="ajax-loader"/>
        </div>
        <div class='table-responsive' style="margin-top: 35px;">
            <table class='table table-striped table-bordered'>
                <tr>
                    <th ng-repeat='col in gridCols' ng-bind='col.LABEL'></th>
                </tr>
                <tr ng-repeat='row in rows'>
                    <td ng-repeat='col in gridCols' ng-bind='row[col.VALOR]'></td>
                </tr>
            </table>
        </div>
        <div class="row" style="margin-top: 35px;" >
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class='form-group'>
                    <div class='btn-group' role='group'>
                        <button id="btnFinalizar" class='btn btn-success' title="Guardar" ng-click='finalizar()' type="button" ng-disabled="disableBtn">
                            <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Guardar
                        </button>
                    </div>
                    <button class='btn btn-info' title="Cancelar" ng-click='cancel()'  type="button">
                        <span class='glyphicon glyphicon-remove'></span>&nbsp;Cancelar
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>