<div class="row" ng-controller="ModuleCtrl">
    <form>
        <div class="row" ng-show="inIngresoCierre&&!inResumen">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <h4 class="be-bold">Efectivo</h4>
                <h5>Ingrese cantidad de billetes o monedas</h5>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <label>Billete 200</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.doscientos"/>
                    </div>
                    <div class="form-group">
                        <label>Billete 100</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.cien"/>
                    </div>
                    <div class="form-group">
                        <label>Billete 50</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.cincuenta"/>
                    </div>
                    <div class="form-group">
                        <label>Billete 20</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.veinte"/>
                    </div>
                    <div class="form-group">
                        <label>Billete 10</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.diez"/>
                    </div>
                    <div class="form-group">
                        <label>Billete 5</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.cinco"/>
                    </div>
                    <div class="form-group">
                        <label>Billete 1</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.uno"/>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                     <div class="form-group">
                        <label>Moneda 1</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.uno_mon"/>
                    </div>
                    <div class="form-group">
                        <label>Moneda 0.50</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.cincuenta_mon"/>
                    </div>
                    <div class="form-group">
                        <label>Moneda 0.25</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.veinticinco_mon"/>
                    </div>
                    <div class="form-group">
                        <label>Moneda 0.10</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.diez_mon"/>
                    </div>
                    <div class="form-group">
                        <label>Moneda 0.05</label>
                        <input class="form-control not-empty" type="text" ng-model="efectivo.cinco_mon"/>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <h4 class="be-bold">Documentos</h4>
                <h5>Vouchers</h5>
                <div class="form-group">
                    <label>Cantidad de vouchers</label>
                    <input class="form-control not-empty" type="text" ng-model="documentos.vouchers"/>
                </div>
                <div class="form-group">
                    <label>Valor total de vouchers</label>
                    <input class="form-control not-empty" type="text" ng-model="documentos.totalVouchers"/>
                </div>
                <h5>Cheques</h5>
                <div class="form-group">
                    <label>Cantidad cheques</label>
                    <input class="form-control not-empty" type="text" ng-model="documentos.cheques"/>
                </div>
                <div class="form-group">
                    <label>Valor total de cheques</label>
                    <input class="form-control not-empty" type="text" ng-model="documentos.totalCheques"/>
                </div>
                <h5>Depósitos y transferencias</h5>
                <div class="form-group">
                    <label>Cantidad depósitos / transferencias</label>
                    <input class="form-control not-empty" type="text" ng-model="documentos.depositos"/>
                </div>
                <div class="form-group">
                    <label>Valor total de depósitos / transferencias</label>
                    <input class="form-control not-empty" type="text" ng-model="documentos.totalDepositos"/>
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-group">
                    <button class="btn btn-lg btn-success" type="text" ng-click="enviar()">Verificada la información. Enviar cierre parcial</button>
                </div>
            </div>
        </div>
        <div class="row" ng-show="!inIngresoCierre&&inResumen">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-condensed">
                        <tr>
                            <th style="text-align: center" colspan="2">Reporte de cierre parcial</th>
                        </tr>
                        <tr>
                            <th>Fecha:</th>
                            <td ng-bind="cierre.fecha_creacion"></td>
                        </tr>
                        <tr>
                            <th>Sucursal:</th>
                            <td ng-bind="cierre.nombre_sucursal"></td>
                        </tr>
                        <tr>
                            <th>Empleado:</th>
                            <td ng-bind="cierre.nombre_empleado"></td>
                        </tr>
                    </table>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered table-condensed">
                        <tr>
                            <th style="text-align: center" colspan="8">Detalle General</th>
                        </tr>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Efectivo</th>
                            <th>Tarjeta</th>
                            <th>Cheque</th>
                            <th>Deposito/TR</th>
                            <th>Crédito</th>
                            <th>Por cobrar</th>
                            <th class="active">Gran total</th>
                        </tr>
                        <tr>
                            <td style="font-style: italic">Venta Unidad</td>
                            <td ng-bind="detalle.unidad_efectivo"></td>
                            <td ng-bind="detalle.unidad_tarjeta"></td>
                            <td ng-bind="detalle.unidad_cheque"></td>
                            <td ng-bind="detalle.unidad_deposito_transf"></td>
                            <td ng-bind="detalle.unidad_credito"></td>
                            <td ng-bind="detalle.unidad_por_cobrar"></td>
                            <td ng-bind="detalle.unidad_total" class="active"></td>
                        </tr>
                        <tr>
                            <td style="font-style: italic">Venta Docena</td>
                            <td ng-bind="detalle.docena_efectivo"></td>
                            <td ng-bind="detalle.docena_tarjeta"></td>
                            <td ng-bind="detalle.docena_cheque"></td>
                            <td ng-bind="detalle.docena_deposito_transf"></td>
                            <td ng-bind="detalle.docena_credito"></td>
                            <td ng-bind="detalle.docena_por_cobrar"></td>
                            <td ng-bind="detalle.docena_total" class="active"></td>
                        </tr>
                        <tr>
                            <td style="font-style: italic">Venta Mayorista</td>
                            <td ng-bind="detalle.mayorista_efectivo"></td>
                            <td ng-bind="detalle.mayorista_tarjeta"></td>
                            <td ng-bind="detalle.mayorista_cheque"></td>
                            <td ng-bind="detalle.mayorista_deposito_transf"></td>
                            <td ng-bind="detalle.mayorista_credito"></td>
                            <td ng-bind="detalle.mayorista_por_cobrar"></td>
                            <td ng-bind="detalle.mayorista_total" class="active"></td>
                        </tr>
                        <tr>
                            <th class="active" style="font-style: italic">Venta total</td>
                            <td class="active" ng-bind="detalle.total_efectivo"></td>
                            <td class="active" ng-bind="detalle.total_tarjeta"></td>
                            <td class="active" ng-bind="detalle.total_cheque"></td>
                            <td class="active" ng-bind="detalle.total_deposito_transf"></td>
                            <td class="active" ng-bind="detalle.total_credito"></td>
                            <td class="active" ng-bind="detalle.total_por_cobrar"></td>
                            <th ng-bind="detalle.gran_total" class="active"></th>
                        </tr>
                        <tr>
                            <td style='font-style: italic'>Pago de clientes</td>
                            <td ng-bind="detalle.cliente_efectivo"></td>
                            <td ng-bind="detalle.cliente_tarjeta"></td>
                            <td ng-bind="detalle.cliente_cheque"></td>
                            <td ng-bind="detalle.cliente_deposito_transf"></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td ng-bind="detalle.cliente_total" class="active"></td>
                        </tr>
                        <tr>
                            <td style='font-style: italic'>Cambios de producto</td>
                            <td ng-bind="detalle.cambio_efectivo"></td>
                            <td ng-bind="detalle.cambio_tarjeta"></td>
                            <td ng-bind="detalle.cambio_cheque"></td>
                            <td ng-bind="detalle.cambio_deposito_transf"></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td ng-bind="detalle.cambio_total" class="active"></td>
                        </tr>
                        <tr>
                            <td style='font-style: italic'>Pagos colectados</td>
                            <td ng-bind='detalle.pagos_colectados'></td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td>&nbsp;</td>
                            <td ng-bind="detalle.pagos_colectados" class="active"></td>
                        </tr>
                        <tr>
                            <th class="active" style="font-style: italic">Total</th>
                            <th class="active" ng-bind="detalle.detalle_efectivo"></th>
                            <th class="active" ng-bind="detalle.detalle_tarjeta"></th>
                            <th class="active" ng-bind="detalle.detalle_cheque"></th>
                            <th class="active" ng-bind="detalle.detalle_deposito_transf"></th>
                            <th class="active" ng-bind="detalle.detalle_credito"></th>
                            <th class="active" ng-bind="detalle.detalle_por_cobrar"></th>
                            <th ng-bind="detalle.detalle_gran_total" class="active"></th>
                        </tr>
                    </table>
                </div>
                <div class='col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                    <div class='table-responsive'>
                        <table class='table table-bordered table-striped table-condensed'>
                            <tr>
                                <th colspan='4' style='text-align: center'>RESUMEN TARJETA</th>
                            </tr>
                            <tr>
                                <th>Concepto</th>
                                <th>Sistema</th>
                                <th>Reportado</th>
                                <th>Cuadró</th>
                            </tr>
                            <tr>
                                <td>Cantidad vouchers</td>
                                <td ng-bind='resDocumentos.sistema_vouchers'></td>
                                <td ng-bind='resDocumentos.reportado_vouchers'></td>
                                <td ng-class='{"success":resDocumentos.sistema_vouchers==resDocumentos.reportado_vouchers,"danger":resDocumentos.sistema_vouchers!=resDocumentos.reportado_vouchers}'>{{resDocumentos.sistema_vouchers==resDocumentos.reportado_vouchers ? "Sí" : "No" }}</td>
                            </tr>
                            <tr>
                                <td>Total vouchers</td>
                                <td ng-bind='resDocumentos.sistema_valoresVoucher'></td>
                                <td ng-bind='resDocumentos.reportado_valoresVoucher'></td>
                                <td ng-class='{"success":resDocumentos.sistema_valoresVoucher==resDocumentos.reportado_valoresVoucher,"danger":resDocumentos.sistema_valoresVoucher!=resDocumentos.reportado_valoresVoucher}'>{{resDocumentos.sistema_valoresVoucher==resDocumentos.reportado_valoresVoucher ? "Sí" : "No" }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class='table-responsive'>
                        <table class='table table-bordered table-striped table-condensed'>
                            <tr>
                                <th colspan='4' style='text-align: center'>RESUMEN CHEQUES</th>
                            </tr>
                            <tr>
                                <th>Concepto</th>
                                <th>Sistema</th>
                                <th>Reportado</th>
                                <th>Cuadró</th>
                            </tr>
                            <tr>
                                <td>Cantidad cheques</td>
                                <td ng-bind='resDocumentos.sistema_cheques'></td>
                                <td ng-bind='resDocumentos.reportado_cheques'></td>
                                <td ng-class='{"success":resDocumentos.sistema_cheques==resDocumentos.reportado_cheques,"danger":resDocumentos.sistema_cheques!=resDocumentos.reportado_cheques}'>{{resDocumentos.sistema_cheques==resDocumentos.reportado_cheques ? "Sí" : "No" }}</td>
                            </tr>
                            <tr>
                                <td>Total cheques</td>
                                <td ng-bind='resDocumentos.sistema_valoresCheques'></td>
                                <td ng-bind='resDocumentos.reportado_valoresCheques'></td>
                                <td ng-class='{"success":resDocumentos.sistema_valoresCheques==resDocumentos.reportado_valoresCheques,"danger":resDocumentos.sistema_valoresCheques!=resDocumentos.reportado_valoresCheques}'>{{resDocumentos.sistema_valoresCheques==resDocumentos.reportado_valoresCheques ? "Sí" : "No" }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class='table-responsive'>
                        <table class='table table-bordered table-striped table-condensed'>
                            <tr>
                                <th colspan='4' style='text-align: center'>RESUMEN DEPOSITOS/TRANSFERENCIAS</th>
                            </tr>
                            <tr>
                                <th>Concepto</th>
                                <th>Sistema</th>
                                <th>Reportado</th>
                                <th>Cuadró</th>
                            </tr>
                            <tr>
                                <td>Cantidad depósitos / transferencias</td>
                                <td ng-bind='resDocumentos.sistema_depositos'></td>
                                <td ng-bind='resDocumentos.reportado_depositos'></td>
                                <td ng-class='{"success":resDocumentos.sistema_depositos==resDocumentos.reportado_depositos,"danger":resDocumentos.sistema_depositos!=resDocumentos.reportado_depositos}'>{{resDocumentos.sistema_depositos==resDocumentos.reportado_depositos ? "Sí" : "No" }}</td>
                            </tr>
                            <tr>
                                <td>Total depósitos / transferencias</td>
                                <td ng-bind='resDocumentos.sistema_valoresDepositos'></td>
                                <td ng-bind='resDocumentos.reportado_valoresDepositos'></td>
                                <td ng-class='{"success":resDocumentos.sistema_valoresDepositos==resDocumentos.reportado_valoresDepositos,"danger":resDocumentos.sistema_valoresDepositos!=resDocumentos.reportado_valoresDepositos}'>{{resDocumentos.sistema_valoresDepositos==resDocumentos.reportado_valoresDepositos ? "Sí" : "No" }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class='col-lg-6 col-md-6 col-sm-12 col-xs-12'>
                    <div class='table-responsive'>
                        <table class='table table-bordered table-condensed'>
                            <tr>
                                <th colspan="4" style='text-align: center'>CUADRE CAJA</th>
                            </tr>
                            <tr>
                                <td style="width: 5%">&nbsp;</td>
                                <td>&nbsp;</td>
                                <th style="width: 10%; font-size: 8px">SISTEMA</th>
                                <th style="width: 10%; font-size: 8px">REPORTADO</th>
                            <tr>
                            <tr>
                                <th colspan="4" style="background-color: #f1f1f1">Recibido</th>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Venta total</i></td>
                                <td ng-bind="cuadre.venta_total"></td>
                                <td ng-bind="cuadre.venta_total"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Pago de clientes</i></td>
                                <td ng-bind="cuadre.pagos_clientes"></td>
                                <td ng-bind="cuadre.pagos_clientes"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Cambios de producto</i></td>
                                <td ng-bind="cuadre.cambios_producto"></td>
                                <td ng-bind="cuadre.cambios_producto"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Pagos colectados</i></td>
                                <td ng-bind="cuadre.pagos_colectados"></td>
                                <td ng-bind="cuadre.pagos_colectados"></td>
                            </tr>
                            <tr>
                                <th style="background-color: #f1f1f1"  colspan="2">Total recibido</th>
                                <td style="background-color: #f1f1f1" ng-bind="cuadre.total_recibido"></td>
                                <td style="background-color: #f1f1f1" ng-bind="cuadre.total_recibido"></td>
                            </tr>
                            <tr>
                                <th colspan="4" style="background-color: #f1f1f1">No efectivo/Pendiente de pago</th>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Total tarjeta</i></td>
                                <td ng-bind="cuadre.sistema_total_tarjeta"></td>
                                <td ng-bind="cuadre.reportado_total_tarjeta"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Total cheques</i></td>
                                <td ng-bind="cuadre.sistema_total_cheques"></td>
                                <td ng-bind="cuadre.reportado_total_cheques"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Total depositos</i></td>
                                <td ng-bind="cuadre.sistema_total_depositos"></td>
                                <td ng-bind="cuadre.reportado_total_depositos"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Total crédito</i></td>
                                <td ng-bind="cuadre.total_credito"></td>
                                <td ng-bind="cuadre.total_credito"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Total por cobrar</i></td>
                                <td ng-bind="cuadre.total_por_cobrar"></td>
                                <td ng-bind="cuadre.total_por_cobrar"></td>
                            </tr>
                            <tr>
                                <th style="background-color: #f1f1f1"  colspan="2">Total No efectivo/Pendiente de pago</th>
                                <td style="background-color: #f1f1f1" ng-bind="cuadre.sistema_total_no_efectivo"></td>
                                <td style="background-color: #f1f1f1" ng-bind="cuadre.reportado_total_no_efectivo"></td>
                            </tr>
                            <tr>
                                <td>&nbsp;</td>
                                <td><i>Gastos</i></td>
                                <td ng-bind="cuadre.total_gastos"></td>
                                <td ng-bind="cuadre.total_gastos"></td>
                            </tr>
                            <tr>
                                <th colspan="2" style="text-align: center; background-color: #dadada">TOTAL INGRESOS EN EFECTIVO</th>
                                <th style="background-color: #dadada" ng-bind="cuadre.sistema_ingresos_efectivo"></th>
                                <th style="background-color: #dadada" ng-bind="cuadre.reportado_ingresos_efectivo"></th>
                            </tr>
                            <tr>
                                <td colspan="2">Efectivo reportado</td>
                                <td ng-bind="cuadre.total_denominaciones"></td>
                                <td ng-bind="cuadre.total_denominaciones"></td>
                            </tr>
                            <tr>
                                <td colspan="2">Fondo</td>
                                <td ng-bind="cuadre.fondo"></td>
                                <td ng-bind="cuadre.fondo"></td>
                            </tr>
                            <tr>
                                <th colspan="2" style="text-align: center; background-color: #dadada">DIFERENCIA EN CAJA</th>
                                <th style="background-color: #dadada" ng-bind="cuadre.sistema_diferencia_cuadre_caja"></th>
                                <th style="background-color: #dadada" ng-bind="cuadre.reportado_diferencia_cuadre_caja"></th>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

