<div class='col-md-12 col-lg-12'>
    <div class="well well-sm row" style="padding-bottom: 0px" ng-show='noMode'>
        <?php 
        if(!$this->onlyEdit){
        ?>
        <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
            <div class='btn-group'>
                <button class='btn btn-primary btn-sm' ng-click='goNew()'>
                    <span class='glyphicon glyphicon-file'></span>&nbsp;Nuevo
                </button>
            </div>
        </div>
        <?php
        }
        ?>
        <div class="form-group col-md-8 col-lg-8 col-sm-6 col-xs-12">
            <label style="display: inline-block">Ordenar por:</label>
            <select style="max-width: 50%; display: inline-block" ng-model="sortBy" class="form-control input-sm">
                <option value="">-- Seleccione --</option>
                <option ng-repeat="col in gridCols" value="{{col.VALOR}}">{{col.LABEL}}</option>
            </select>
        </div>
    </div>
        
    <div class='table-responsive'>
        <table class='table table-striped table-bordered' ng-show='noMode'>
            <tr>
                <th ng-repeat='col in gridCols' ng-bind='col.LABEL'></th>
            </tr>
            <tr>
                <?php
                    foreach ($this->gridCols as $key => $value) {
                ?>
                        <td><input type='text' ng-model='search.<?php echo $value ?>'/></td>
                <?php
                    }
                ?>
            </tr>
            <tr ng-class="{info:row.selected}" ng-click='selectRow(row)' ng-repeat='row in rows | filter:search | orderBy: sortBy'>
                <td ng-repeat='col in gridCols' ng-bind='row[col.VALOR]'></td>
            </tr>
        </table>
    </div>
    <form ng-show='editMode||newMode' class='col-md-12 col-lg-12' id="mantForm" method="post">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <?php
            $i = 1;
            foreach ($this->fields as $f) {
                if($f instanceof FastField){
                    $f->build();
                    if($i == 8){
                        ?>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <?php
                        $i = 0;
                    }
                    $i++;
                }
            }
            ?>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class='form-group'>
                <div class='btn-group' role='group'>
                    <button class='btn btn-success' title="Guardar" ng-click='doSave()' type="button">
                        <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Guardar
                    </button>
                    <?php 
                    if(!$this->onlyEdit){
                        ?>
                    <button class='btn btn-danger' title="Eliminar" ng-click='doDelete()' ng-if="editMode" type="button">
                        <span class='glyphicon glyphicon-trash'></span>&nbsp;Eliminar
                    </button>
                        <?php
                    }
                    ?>
                </div>
                <div class='btn-group' role='group'>
                    <button class='btn btn-primary' title="Anterior" ng-click='prev()'  type="button" ng-if="editMode">
                        <span class='glyphicon glyphicon-chevron-left'></span>&nbsp;Anterior
                    </button>
                    <button class='btn btn-primary' title="Siguiente" ng-click='next()'  type="button" ng-if="editMode">
                        Siguiente&nbsp;<span class='glyphicon glyphicon-chevron-right'></span>
                    </button>
                </div>
                <button class='btn btn-info' title="Cancelar" ng-click='cancel()'  type="button">
                    <span class='glyphicon glyphicon-remove'></span>&nbsp;Cancelar
                </button>
            </div>
        </div>
    </form>
</div>