<div ng-controller="ModuleCtrl">
    <form id="mantForm" name="mantForm" method="post">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <fieldset>
                    <legend>
                        Por Archivo:
                        <input ng-model="porArchivo" type="checkbox" name="porArchivo" ng-click="actualizarChkBxFiltro()"/>
                    </legend>
                </fieldset>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" ng-show="porArchivo">
                <div class='form-group form-group-sm'>
                    <label for='file' class='control-label'>Archivo Excel</label>
                    <input ng-model="file" type="file" name="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"  value="file" onchange="angular.element(this).scope().uploadFile(this.files)"/>
                    <input ng-model="file" type="hidden" class='form-control'/>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <fieldset>
                    <legend>
                        Por Filtros:
                        <input ng-model="porFiltro" type="checkbox" name="porFiltro" ng-click="actualizarChkBxArchivo()"/>
                    </legend>
                </fieldset>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" ng-show="porFiltro">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class='form-group form-group-sm'>
                            <label for='id_tipo' class='control-label'>Categoría</label>
                            <select name="id_tipo" id="id_tipo" ng-model="id_tipo" type="select" required class='form-control' ng-change="filtrar()">
                                <option ng-repeat="categoria in categorias" value="{{categoria.id_tipo}}">{{categoria.nombre}}</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class='form-group form-group-sm'>
                            <label for='id_sucursal' class='control-label'>Bodega</label>
                            <select name="id_sucursal" id="id_sucursal" ng-model="id_sucursal" type="select" required class='form-control' ng-change="filtrar()">
                                <option ng-repeat="sucursal in sucursales" value="{{sucursal.id_sucursal}}">{{sucursal.nombre}}</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='table-responsive' style="margin-top: 35px;" ng-show="porFiltro">
            <table class='table table-striped table-bordered'>
                <tr>
                    <th ng-repeat='col in gridCols' ng-bind='col.LABEL'></th>
                </tr>
                <tr ng-repeat='row in rows'>
                    <td ng-repeat='col in gridCols' ng-bind='row[col.VALOR]'></td>
                </tr>
            </table>
        </div>
        <div class="row" style="margin-top: 35px;" >
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class='form-group'>
                    <div class='btn-group' role='group'>
                        <button id="btnFinalizar" class='btn btn-success' title="Guardar" ng-click='finalizar()' type="button" ng-disabled="disableBtn">
                            <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Generar
                        </button>
                    </div>
                    <button class='btn btn-info' title="Cancelar" ng-click='cancel()' type="button">
                        <span class='glyphicon glyphicon-remove'></span>&nbsp;Cancelar
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>