<div ng-controller="ModuleCtrl">
    <div class="row">
        <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12">
            <form>
                <div class="form-group">
                    <label>Cantidad</label>
                    <input class="form-control not-empty" type="text" ng-model="cantidad"/>
                </div>
                <div class="form-group">
                    <label>Motivo</label>
                    <textarea class="form-control" ng-model="motivo"></textarea>
                </div>
                <div class="form-group">
                    <label>Contraseña de gastos</label>
                    <input class="form-control" type="password" ng-model="pass" />
                </div>
                <div class="form-group">
                    <button class="btn btn-success" ng-click="finalizar()">Enviar</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">    
        <div class="col-lg-12 col-md-12 col-sm-8 col-xs-12">    
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed table-hover">
                    <tr>
                        <td colspan="7">
                            Buscar: <input id="filterGastos" type="text" ng-model="filterGastos"/>
                        </td>
                    </tr>
                    <tr>
                        <th>Id</th>
                        <th>Descripci&oacute;n</th>
                        <th>Fecha</th>
                        <th>Empresa</th>
                        <th>Sucursal</th>
                        <th>Empleado</th>
                        <th>Cantidad</th>
                    </tr>
                    <tr ng-repeat="g in gastos | filter: filterGastos">
                        <td ng-bind="g.id_gasto"></td>
                        <td ng-bind="g.descripcion"></td>
                        <td ng-bind="g.fecha"></td>
                        <td ng-bind="g.empresa"></td>
                        <td ng-bind="g.sucursal"></td>
                        <td ng-bind="g.empleado"></td>
                        <td ng-bind="g.cantidad"></td>
                    </tr>
                </table>
            </div>
        </div>
    </div> 
</div>