<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-controller="ModuleCtrl" style="margin-bottom: 20px;">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-show="!inNuevoEnvio&&!inRecibirEnvio">
        <div class="table-responsive">
            <h4>Pendientes por recibir</h4>
            <table class="table table-striped table-hover table-bordered">
                <tr>
                    <th>Origen</th>
                    <th>Productos</th>
                    <th>Comentario</th>
                    <th>Opciones</th>
                </tr>
                <tr ng-repeat="e in recibir">
                    <td ng-bind="e.origen_nombre"></td>
                    <td ng-bind="e.productos.length"></td>
                    <td ng-bind="e.comentario_envio"></td>
                    <td>
                        <button class='btn btn-primary btn-sm' ng-click='doRecibir(e)'>Recibir</button>
                    </td>
                </tr>
            </table>
        </div>
        <div class="table-responsive">
            <h4>Envios pendientes 
                <button class="btn btn-success btn-sm" ng-click="doNew()">
                    <span class="glyphicon glyphicon-plus-sign"></span>&nbsp;Nuevo
                </button>
            </h4>
            <table class="table table-striped table-hover table-bordered">
                <tr>
                    <th>Destino</th>
                    <th>Hora / Fecha</th>
                    <th>Comentario</th>
                    <th>Productos</th>
                </tr>
                <tr ng-repeat="e in enviados">
                    <td ng-bind="e.destino_nombre"></td>
                    <td ng-bind='e.fecha_creacion'></td>
                    <td ng-bind="e.comentario_envio"></td>
                    <td>
                        <div ng-repeat='p in e.productos'>
                            <span class='be-bold' ng-bind='p.nombre_marca + " - " + p.nombre + " - " + p.unidades'></span>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-show="inRecibirEnvio&&!inNuevoEnvio">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
            <button class="btn btn-primary btn-xs" type="button" ng-click="inNuevoEnvio=false; inRecibirEnvio=false;">
                <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Regresar
            </button>
        </div>
        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class='panel panel-default'>
                <div class='panel-heading'>
                    <h4 class='panel-title'>Información del envío</h4>
                </div>
                <div class='panel-body'>
                    <ul class='list-group'>
                        <li class='list-group-item'>
                            <span class='be-bold'>Origen</span>:&nbsp;<span ng-bind='envioActual.origen_nombre'></span>
                        </li>
                        <li class='list-group-item'>
                            <span class='be-bold'>Usuario creador</span>:&nbsp;<span ng-bind='envioActual.empleado_origen'></span>
                        </li>
                        <li class='list-group-item'>
                            <span class='be-bold'>Fecha / hora</span>:&nbsp;<span ng-bind='envioActual.fecha_creacion'></span>
                        </li>
                        <li class='list-group-item'>
                            <span class='be-bold'>Productos</span>:&nbsp;
                            <div ng-repeat='p in envioActual.productos'>
                                <span class='be-bold' ng-bind='p.nombre_marca + " - " + p.nombre + " - " + p.unidades'></span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
            <div class='panel panel-default'>
                <div class='panel-heading'>
                    <h4 class='panel-title'>Finalizar y recibir</h4>
                </div>
                <div class='panel-body'>
                    <div class='form-group'>
                        <label>Comentario recepcion</label>
                        <textarea class='form-control' ng-model='envioActual.comentario_destino'></textarea>
                    </div>
                    <button class='btn btn-lg btn-success' ng-show='envioActual.comentario_destino!=""' ng-click='finalizarRecepcion()'>Finalizar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-show="inNuevoEnvio&&!inRecibirEnvio">
        <button class="btn btn-primary btn-xs" type="button" ng-click="inNuevoEnvio=false; inRecibirEnvio=false;">
            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Regresar
        </button>
        <div class="modal fade" id="finModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Finalizar envio</h4>
                    </div>
                    <div class="modal-body">
                        <label class="control-label">Comentario del Envío:</label>
                        <textarea ng-model="envioActual.comentario_envio" class="form-control"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                        <button class="btn btn-success" ng-click="finalizarEnvio()" ng-if="productosSel.length>0&&envioActual.comentario_envio!=''">Finalizar</button>
                    </div>
                </div>
            </div>
        </div>
        <h3>Nuevo envío</h3>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Origen</h4>
                </div>
                <div class="panel-body">
                    <select ng-model="envioActual.id_sucursal_origen" class="form-control" ng-disabled="!esSuperUsuario">
                        <option ng-repeat="s in sucursales"  value="{{s.id_sucursal}}">{{s.nombre}}</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Destino</h4>
                </div>
                <div class="panel-body">
                    <select ng-model="envioActual.id_sucursal_destino" class="form-control">
                        <option ng-repeat="s in sucursales" ng-if="(s.es_actual&&esSuperUsuario)||!s.es_actual" value="{{s.id_sucursal}}">{{s.nombre}}</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h3 class="text-bold">Productos</h3>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <tr>
                        <th style="width: 15.8%">Código producto</th>
                        <th style="width: 15.8%">Nombre</th>
                        <th style="width: 15.8%">Descripción</th>
                        <th style="width: 15.8%">SKU</th>
                        <th style="width: 15.8%">Proveedor</th>
                        <th style="width: 5%">En sucursal</th>
                        <th style="width: 12.6%">Opciones</th>
                    </tr>
                    <tr>
                        <td>
                            <input type="text" class="form-control" ng-model="search.codigo_producto"/>
                        </td>
                        <td>
                            <input type="text" class="form-control" ng-model="search.nombre"/>
                        </td>
                        <td>
                            <input type="text" class="form-control" ng-model="search.descripcion"/>
                        </td>
                        <td>
                            <input type="text" class="form-control" ng-model="search.sku"/>
                        </td>
                        <td>
                            <input type="text" class="form-control" ng-model="search.proveedor_label"/>
                        </td>
                        <td>&nbsp;</td>
                        <td><button type="button" ng-click="clearFilter()" class="btn btn-sm btn-primary">Limpiar filtro</button></td>
                    </tr>
                </table>
                <div style="max-height: 250px; overflow-y: auto" >
                    <table class="table table-striped table-bordered table-condensed table-hover">
                        <tr ng-repeat="p in productos | filter:search">
                            <td style="width: 16%" ng-bind="p.codigo_producto"></td>
                            <td style="width: 16%" ng-bind="p.nombre"></td>
                            <td style="width: 16%" ng-bind="p.descripcion"></td>
                            <td style="width: 16%" ng-bind="p.sku"></td>
                            <td style="width: 16%" ng-bind="p.proveedor_label"></td>
                            <td style="width: 5%; font-size: 21px;" class="text-bold" ng-bind="p.stock" ng-class="{'text-success':p.stock>0,'text-danger':p.stock<=0}"></td>
                            <td style="width: 10%">
                                <button class="btn btn-success btn-sm" ng-click="addProducto(p)">
                                    <span class="glyphicon glyphicon-plus-sign"></span>
                                </button>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div ng-show="productosSel.length>0" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h3 class="text-bold">Detalle envio</h3>
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover">
                    <tr>
                        <th>Código producto</th>
                        <th>Nombre</th>
                        <th>En Sucursal</th>
                        <th>A Enviar</th>
                        <th>&nbsp;</th>
                    </tr>
                    <tr ng-repeat="p in productosSel">
                        <td ng-bind="p.codigo_producto"></td>
                        <td ng-bind="p.nombre"></td>
                        <td class="text-bolder" ng-bind="p.stock" ng-class="{'text-success':p.stock>0,'text-danger':p.stock<=0}"></td>
                        <td ng-class="{'danger': p.unidades>p.stock}">
                            <input type="text" class="modField" ng-model="p.unidades"/>
                        </td>
                        <td>
                            <button class="btn btn-danger btn-sm" ng-click="removeItem(p)">
                                <span class="glyphicon glyphicon-remove-sign"></span>
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
            <button class="btn btn-primary btn-lg" ng-show='productosSel.length>0' ng-click="finalizarModal()">Realizar envío</button>
            <button class="btn btn-danger btn-lg" ng-click="cancelar()">Cancelar</button>
        </div>
    </div>
</div>
