<style type="text/css">
    .anyClass {
        height:400px;
        overflow-y: scroll;
    }
    .color-red {
        color: red;
    }
    .color-green {
        color: green;
    }
</style>
<div ng-controller="ModuleCtrl">
    <div class="modal fade" tabindex="-1" role="dialog" id="clientesModal">
        <div class="modal-dialog" style="max-width: 700px; height: 500px;">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Clientes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class='table-responsive anyClass'>
                        <table class='table table-striped table-bordered'>
                            <tr>
                                <th>Identificacion</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                            </tr>
                            <tr>
                                <td><input id="identificacion" type='text' ng-model="search.identificacion"/></td>
                                <td><input id="nombres" type='text' ng-model="search.nombres"/></td>
                                <td><input id="apellidos" type='text' ng-model="search.apellidos"/></td>
                            </tr>
                            <tr ng-class="{info:row.selected}" ng-click='selectRow(row)' ng-repeat='row in rows | filter:search | orderBy: sortBy'>
                                <td ng-bind="row['identificacion']"></td>
                                <td ng-bind="row['nombres']"></td>
                                <td ng-bind="row['apellidos']"></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog" id="consignacionesModal">
        <div class="modal-dialog" role="document" style="max-width: 700px; height: 500px;">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Clientes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class='table-responsive anyClass'>
                        <table class='table table-striped table-bordered'>
                            <tr>
                                <th>id_movimiento_sucursales</th>
                                <th>comentario_envio</th>
                                <th>fecha_creacion</th>
                            </tr>
                            <tr>
                                <td><input type='text' ng-model="search.id_movimiento_sucursales"/></td>
                                <td><input type='text' ng-model="search.comentario_envio"/></td>
                                <td><input type='text' ng-model="search.fecha_creacion"/></td>
                            </tr>
                            <tr ng-class="{info:row.selected}" ng-click='selectRowConsignaciones(row)' ng-repeat='row in consignaciones | filter:search | orderBy: sortBy'>
                                <td ng-bind="row['id_movimiento_sucursales']"></td>
                                <td ng-bind="row['comentario_envio']"></td>
                                <td ng-bind="row['fecha_creacion']"></td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 bg-light mb-3">
            <div class="input-group input-group-lg my-3">
                <div class="input-group-prepend">
                    <span class="input-group-text"><span class="cui-magnifying-glass"></span></span>
                </div>
                <input type="text" id="producto" class="form-control" placeholder="Buscar Productos..." aria-label="Search" ng-model="search" autocomplete="off" style="font-size:0.8rem;">
            </div>
            <div class="row anyClass">
                <div ng-repeat="prod in productos | filter:search" class="col-12 col-md-4">
                        <figure class="figure btn btn-ghost-light">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                    <input class="form-control form-control-sm" type="number" ng-model="prod.cant_reingreso" min="0" value="0">
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                    <button class='btn btn-success btn-sm' title="Agregar" ng-click='reIngresar(prod)' type="button">
                                        <span class='cui-chevron-right'></span>
                                    </button>
                                </div>
                            </div>
                            <span class="d-inline-block" tabindex="0" data-toggle="tooltip" title="{{prod.unidades-prod.cant_reingreso}} unidades restantes" >
                                <img ng-src="media/uploads/{{prod.imagen}}" alt="{{prod.descripcion}}" class="img-thumbnail" ng-click="reIngresarUno(prod)">
                                <figcaption class="figure-caption">
                                    <label class="col-sm-2 col-form-label col-form-label-sm">{{prod.nombre}}</label>
                                </figcaption>
                            </span>
                        </figure>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                    <label class="color-green">Entregado - {{lastSelectedConsig.total_entregado}}</label>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <button type="button" class="btn btn-pill btn-success" ng-show="lastSelectedConsig.total_reingreso === lastSelectedConsig.compra_minima" ng-click="generarFactura()">Generar Factura</button>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12" style="text-align: right;">
                    <label ng-class="{'color-red': lastSelectedConsig.total_reingreso === lastSelectedConsig.compra_minima}">Reingreso - {{lastSelectedConsig.total_reingreso}}/{{lastSelectedConsig.compra_minima}}</label>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 text-white bg-secondary mb-3">
            <div class="input-group input-group-lg my-3" ng-click='buscar()' data-toggle="modal" data-target="#clientesModal">
                <div class="input-group-prepend" >
                    <span class="input-group-text"><span class="cui-magnifying-glass"></span></span>
                </div>
                <input type="text" id="cliente" ng-model="cliente" class="form-control" placeholder="Buscar Cliente..." aria-label="Search" autocomplete="off" style="font-size:0.8rem;">
            </div>
            <div class=" anyClass">
                <div class='table-responsive'>
                    <table class="table table-dark table-striped" style="font-size:0.8rem; ">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Cod. Prod.</th>
                                <th scope="col">Cantidad</th>
                                <th scope="col">Precio</th>
                                <th scope="col">Subtotal</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat='prod in productos_facturar' >
                                <th scope="row">{{($index+1)}}</th>
                                <td ng-bind="prod.codigo_origen"></td>
                                <td ng-bind="prod.cant_facturar"></td>
                                <td ng-bind="prod.precio_descuento"></td>
                                <td ng-bind="prod.sub_total | number:2"></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th scope="row">Total</th>
                                <td></td>
                                <td></td>
                                <td></td>
                                <th scope="row">{{productos_facturar.sum("sub_total") | number:2}}</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                </div>
                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <button type="button" class="btn btn-pill btn-success" ng-show="facturar" ng-click="facturar()">Facturar</button>
                </div>
                <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                </div>
            </div>
        </div>
    </div>
</div>