<div ng-controller="ModuleCtrl" style="min-height: 400px">
    <div class="row">    
        <div class="col-lg-12 col-md-12 col-sm-8 col-xs-12">
        <div class="well">
            <div class="row">
                
                <div class="col-12 col-md-2 form-group">
                    Bodega: <select id="bodega" class="form-control searchEnter" ng-model="search.id_sucursal" ng-options="s.id_sucursal as s.nombre for s in sucursales">
                        <option value="">-- Seleccione bodega --</option>
                    </select>
                </div>

                <div class="col-12 col-md-2 form-group">
                    Nombres: <input id="nombres" class="form-control searchEnter" type="text" ng-model="search.nombres" />
                </div>
                <div class="col-12 col-md-2 form-group">
                    Apellidos: <input class="form-control searchEnter" type="text" ng-model="search.apellidos" />
                </div>
                <div class="col-12 col-md-2 form-group">
                    Fecha de: <input class="form-control searchEnter" id="fechaDe" type="text" ng-change="" ng-model="search.fechaDe" />
                </div>
                <div class="col-12 col-md-2 form-group">
                    Fecha a: <input class="form-control searchEnter" id="fechaA" type="text" ng-model="search.fechaA" />
                </div>
                <div class="col-12 col-md-2 form-group pt-3">
                    <button class="btn btn-success" ng-disabled="!isAdmin&&!search.id_sucursal" ng-click="searchVentas()">
                        <i class="cui-refresh"></i>&nbsp;Refrescar
                    </button>
                    <button class="btn btn-info" ng-click="generaExcel()" ng-hide="(!isAdmin&&!search.id_sucursal)||!sucursales.length||!ventas.length">
                        <i class="cui-file"></i>
                    </button>
                </div>
            </div>
        </div>    
            <div class="table-responsive">
                <table class="table table-striped table-bordered table-condensed">
                    <tr>
                        <th>Fecha</th>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Bodega</th>
                        <th>Vendedor</th>
                        <th>Total</th>
                        <th>Piezas</th>
                        <th>Tipo</th>
                    </tr>
                    <tr ng-repeat="v in ventas">
                        <td ng-bind="v.fecha_creacion"></td>
                        <td ng-bind="v.nombres"></td>
                        <td ng-bind="v.apellidos"></td>
                        <td ng-bind="v.nombre_bodega"></td>
                        <td ng-bind="v.usuario_venta"></td>
                        <th ng-bind="v.total_real | currency : 'Q' : 2"></th>
                        <td ng-bind="v.piezas | number : 0"></td>
                        <td ng-bind="v.tipo_venta"></td>
                    </tr>
                </table>
            </div>
        </div>
    </div> 
</div>