<div class='col-md-12 col-lg-12' ng-controller="ModuleCtrl">
    <form class='col-md-12 col-lg-12' id="mantForm" name="mantForm" method="post">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <fieldset>
                    <legend>Bodega Origen:</legend>
                    <div class='form-group form-group-sm'>
                        <select name="idSucursalOrigen" id="idSucursalOrigen" ng-model="idSucursalOrigen" type="select" required class='form-control'>
                            <option ng-repeat="sucursal in sucursalesOrigen" value="{{sucursal.id_sucursal}}">{{sucursal.nombre}}</option>
                        </select>
                    </div>
                </fieldset>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <fieldset>
                    <legend>Bodega Destino:</legend>
                    <select name="idSucursalDestino" id="idSucursalDestino" ng-model="idSucursalDestino" type="select" required class='form-control'>
                        <option ng-repeat="sucursal in sucursalesDestino" value="{{sucursal.id_sucursal}}">{{sucursal.nombre}}</option>
                    </select>
                </fieldset>
            </div>
        </div>
        <div class="row" style="margin-top: 35px;">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class='form-group form-group-sm'>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 35px;" >
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class='form-group'>
                    <div class='btn-group' role='group'>
                        <button id="btnFinalizar" class='btn btn-success' title="Guardar" ng-click='finalizar()' type="button" ng-disabled="disableBtn">
                            <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Trasladar
                        </button>
                    </div>
                    <button class='btn btn-info' title="Cancelar" ng-click='cancel()'  type="button">
                        <span class='glyphicon glyphicon-remove'></span>&nbsp;Cancelar
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>