<div class='col-md-12 col-lg-12' ng-controller="ModuleCtrl">
    <form class='col-md-12 col-lg-12' id="mantForm" name="mantForm" method="post">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <fieldset>
                    <legend>Bodega Origen:</legend>
                    <div class='form-group form-group-sm'>
                        <select name="idSucursalOrigen" id="idSucursalOrigen" ng-model="idSucursalOrigen" type="select" required class='form-control' ng-change="filtarProductos()">
                            <option ng-repeat="sucursal in sucursalesOrigen" value="{{sucursal.id_sucursal}}">{{sucursal.nombre}}</option>
                        </select>
                    </div>
                </fieldset>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <fieldset>
                    <legend>Bodega Destino:</legend>
                    <select name="idSucursalDestino" id="idSucursalDestino" ng-model="idSucursalDestino" type="select" required class='form-control' ng-change="selBodegaDestino()">
                        <option ng-repeat="sucursal in sucursalesDestino" value="{{sucursal.id_sucursal}}">{{sucursal.nombre}}</option>
                    </select>
                </fieldset>
            </div>
        </div>
        <div class="row" style="margin-top: 35px;">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class='form-group'>
                            <div class='btn-group' role='group'>
                                <button id="btnTrasladarTodo" class='btn btn-success' title="Trasladar Todo" ng-click='trasladarTodo()' type="button">
                                    <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Trasladar Todo
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class='checkbox'>
                            <label>
                                Es Consignación
                                <input ng-model="esConsignacion" type="checkbox" name='esConsignacion' placeholder='' />
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" ng-show="esConsignacion">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class='form-group form-group-sm'>
                            <label for='diasConsignar' class='control-label'>Dias a Consignar</label>
                            <input ng-model="diasConsignar" type="number" class='form-control' name='diasConsignar' placeholder='0' min="1" max="100" size="5"/>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class='form-group form-group-sm'>
                            <label for='porcentajeCompraMinima' class='control-label'>Porcentaje Compra Mínima</label>
                            <input ng-model="porcentajeCompraMinima" type="number" class='form-control' name='porcentajeCompraMinima' placeholder='0' min="1" max="100" size="5"/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group form-group-sm">
                            <label style="display: inline-block">Cliente que Recibe</label>
                            <select name="idClienteRecibe" id="idClienteRecibe" ng-model="idClienteRecibe" type="select" required class='form-control'>
                                <option value="">-- Seleccione uno --</option>
                                <option ng-repeat="cliente in clientesBodegas" value="{{cliente.id_cliente}}">{{cliente.cliente_nombre}}</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class='table-responsive'>
                    <table class='table table-striped table-bordered table-sm'>
                        <tr>
                            <th style="width: 25px;text-align: center;">Código Producto</th>
                            <th style="text-align: center;">Nombre</th>
                            <th style="text-align: center;">Descripción</th>
                            <th style="text-align: center;">Categoría</th>
                            <th style="text-align: center;">Existencia</th>
                            <th style="width: 25px;text-align: center;">Cantidad a Trasladar</th>
                        </tr>
                        <tr>
                            <td><input type='text' class='form-control form-control-sm' ng-model="search.codigo_origen"/></td>
                            <td><input type='text' class='form-control form-control-sm' ng-model="search.nombre"/></td>
                            <td><input type='text' class='form-control form-control-sm' ng-model="search.descripcion"/></td>
                            <td><input type='text' class='form-control form-control-sm' ng-model="search.nombre_tipo"/></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr ng-repeat='row in rows | filter:search | orderBy: sortBy'>
                            <td ng-bind="row['codigo_origen']"></td>
                            <td ng-bind="row['nombre']"></td>
                            <td ng-bind="row['descripcion']"></td>
                            <td ng-bind="row['nombre_tipo']"></td>
                            <td ng-bind="row['haber']"></td>
                            <td>
                                <input type="number" class='form-control form-control-sm' name="cantidad" ng-model="row['cantidad']" size="5" min="0">
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top: 35px;" >
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class='form-group'>
                    <div class='btn-group' role='group'>
                        <button id="btnFinalizar" class='btn btn-success' title="Guardar" ng-click='finalizar()' type="button" ng-disabled="disableBtn">
                            <span class='glyphicon glyphicon-floppy-saved'></span>&nbsp;Trasladar
                        </button>
                    </div>
                    <button class='btn btn-info' title="Cancelar" ng-click='cancel()'  type="button">
                        <span class='glyphicon glyphicon-remove'></span>&nbsp;Cancelar
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>