<div class="row" ng-controller="ModuleCtrl">
    <div class="modal fade" id="passCat">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Contraseña cambiar precio</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <input type="password" class="form-control" id="passCambiarPrecio" ng-model="passCambiarPrecio"/>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" id="cerrarModalPassBtn" ng-click="passCambiarPrecio='';$('#passCat').modal('hide');" type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="ventaCat">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Contraseña cambiar venta</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            Tipo venta: 
                            <select ng-model="ventaModificadaTipo" class='form-control'>
                                <option value='UNIDAD'>Unidad</option>
                                <option value='DOCENA'>Docena</option>
                                <option value='MAYORISTA'>Mayorista</option>
                            </select>
                        </div>
                        <div class='form-group'>
                            Contraseña: <input type="password" class="form-control" id="passCambiarVenta" ng-model="passCambiarVenta"/>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button class='btn btn-primary' ng-click="modificarVenta()">Modificar</button>
                    <button class="btn btn-danger" data-dismiss='modal' type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="clientesCat">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Seleccionar cliente</h4>
                </div>
                <div class="modal-body">
                    <form ng-show="newClienteMode">
                        <div class="form-group">
                            <label class="control-label">Identificación</label>
                            <input type="text" class="form-control" ng-model="nuevoCliente.id_personal"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Nombres</label>
                            <input type="text" class="form-control" ng-model="nuevoCliente.nombres"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Apellidos</label>
                            <input type="text" class="form-control" ng-model="nuevoCliente.apellidos"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">NIT</label>
                            <input type="text" class="form-control" ng-model="nuevoCliente.nit"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Teléfono</label>
                            <input type="text" class="form-control" ng-model="nuevoCliente.telefono"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Correo electrónico</label>
                            <input type="text" class="form-control" ng-model="nuevoCliente.correo"/>
                        </div>
                        <button class="btn btn-info" ng-click="newClienteMode=false">
                            <span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Regresar
                        </button>
                        <button class="btn btn-success" ng-show="nuevoCliente.nombres!=''&&nuevoCliente.apellidos!=''" ng-click="guardarCliente()">Guardar</button>
                    </form>
                    <div class="table-responsive" ng-show="!newClienteMode">
                        <table class="table table-striped table-bordered table-condensed table-hover">
                            <tr>
                                <td colspan="5">
                                    Buscar: <input id="filterClientes" type="text" ng-model="filterClientes"/>
                                    <button class="btn btn-primary" ng-click="newClienteMode=true">
                                        <span class="glyphicon glyphicon-ok-circle"></span>&nbsp;Nuevo cliente
                                    </button>
                                </td>
                            </tr>
                            <tr>
                                <th>Id</th>
                                <th>Nombres</th>
                                <th>Apellidos</th>
                                <th>Nit</th>
                                <th>Opciones</th>
                            </tr>
                            <tr ng-repeat="c in clientes | filter: filterClientes">
                                <td ng-bind="c.id_personal"></td>
                                <td ng-bind="c.nombres"></td>
                                <td ng-bind="c.apellidos"></td>
                                <td ng-bind="c.nit"></td>
                                <td>
                                    <button class="btn btn-success" ng-click="selectCliente(c)">
                                        <span class="glyphicon glyphicon-ok-circle"></span>
                                    </button>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-danger" id="cerrarModalClienteBtn" type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="formaDePagoCat">
        <div class="modal-dialog modal-lg" style="width: 90%">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Forma de pago</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <h4>Forma de pago</h4>
                            <form>
                                <div class="form-group">
                                    <label>Efectivo</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.efectivo" id="efectivo" />
                                </div>
                                <div class="form-group">
                                    <label>Tarjeta</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.tarjeta" ng-change="recargo()" />
                                    <span class="text-warning be-bold" ng-if="formaDePago.tarjeta>0&&totalVentaMayorista.selected">Aplica un recargo</span>
                                </div>
                                <div class="form-group" ng-show="cliente.tiene_credito==1">
                                    <label>Crédito</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.credito"/>
                                </div>
                                <div class="form-group">
                                    <label>Por cobrar</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.por_cobrar"/>
                                </div>
                                <div class="form-group">
                                    <label>Cheque</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.cheque" />
                                </div>
                                <div ng-show="formaDePago.cheque>0">
                                    <div class="form-group">
                                        <label>Número de cheque</label>
                                        <input type="text" class="not-empty form-control" ng-model="formaDePago.numero_cheque" />
                                    </div>
                                    <div class="form-group">
                                        <label>Banco del cheque</label>
                                        <select class="form-control" ng-model="formaDePago.id_banco">
                                            <option value=''>-- Selecciona uno --</option>
                                            <option value="{{b.id_banco}}" ng-repeat="b in bancos">{{b.nombre}}</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Depósito/Transferencia</label>
                                    <input type="text" class="not-empty form-control" ng-model="formaDePago.deposito" />
                                </div>
                                <div ng-show="formaDePago.deposito>0">
                                    <div class="form-group">
                                        <label>Número</label>
                                        <input type="text" class="form-control" ng-model="formaDePago.numero_deposito" />
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <div style="max-height: 150px; overflow-y: auto">
                                <h4>Cargos adicionales</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-condensed">
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Valor</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                        <tr ng-repeat="a in adicionalesSel">
                                            <td ng-bind="a.nombre"></td>
                                            <td ng-bind="a.valor"></td>
                                            <td>
                                                <button class="btn btn-danger btn-xs" ng-click="quitarAdicional(a)">
                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered table-condensed">
                                        <tr>
                                            <td colspan="3">
                                                Buscar: <input type="text" ng-model="filterAdicionales"/>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Valor</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                        <tr ng-repeat="a in adicionales | filter: filterAdicionales">
                                            <td ng-bind="a.nombre"></td>
                                            <td ng-bind="a.valor"></td>
                                            <td>
                                                <button class="btn btn-success btn-xs" ng-click="addAdicional(a)">
                                                    <span class="glyphicon glyphicon-plus-sign"></span>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <div style="max-height:150px; overflow-y: auto">
                                <h4>Descuento</h4>
                                <div class="table-responsive" ng-show="descSeleccionado.porcentaje">
                                    <table class="table table-striped table-bordered table-condensed">
                                        <tr>
                                            <th>Porcentaje</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                        <tr>
                                            <td ng-bind="descSeleccionado.porcentaje"></td>
                                            <td>
                                                <button class="btn btn-danger btn-xs" ng-click="quitarDescuento()">
                                                    <span class="glyphicon glyphicon-remove-sign"></span>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                                <div class="table-responsive" ng-show="!descSeleccionado.porcentaje">
                                    <table class="table table-striped table-bordered table-condensed">
                                        <tr>
                                            <td colspan="2">
                                                Buscar: <input type="text" ng-model="filterDescuentos"/>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>Nombre</th>
                                            <th>Valor</th>
                                            <th>&nbsp;</th>
                                        </tr>
                                        <tr ng-repeat="d in descuentos | filter: filterDescuentos">
                                            <td ng-bind="d.porcentaje"></td>
                                            <td>
                                                <button class="btn btn-success btn-xs" ng-click="addDescuento(d)">
                                                    <span class="glyphicon glyphicon-plus-sign"></span>
                                                </button>
                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                            <h4>Resumen</h4>
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered">
                                    <tr>
                                        <th>Producto</th>
                                        <td ng-bind="totalVenta"></td>
                                    </tr>
                                    <tr>
                                        <th>Cargos adicionales</th>
                                        <td ng-bind="totalAdicionales"></td>
                                    </tr>
                                    <th>TOTAL VENTA</th>
                                    <th  style="font-size: 21px" ng-bind="totalMaster"></th>
                                </table>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" ng-model="genera"> Generar
                                </label>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" ng-click="terminarVenta()">
                        <span class="glyphicon glyphicon-floppy-saved"></span>&nbsp;Terminar venta
                    </button>
                    <button class="btn btn-danger" data-dismiss='modal' type="button">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-if='!validSale'>
        <div class='alert alert-warning' ng-bind='notValidMessage'></div>
    </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-if='validSale'>
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-condensed">
                <tr>
                    <td style="width: 20%">
                        <span class="be-bold" style="font-size: 21px">Cliente</span>
                    </td>
                    <td style="font-size: 15px; width: 20%" class="text-center" ng-bind="cliente.id_personal"></td>
                    <td style="font-size: 15px; width: 20%" class="text-center" ng-bind="cliente.nombres"></td>
                    <td style="font-size: 15px; width: 20%" class="text-center" ng-bind="cliente.apellidos"></td>
                    <td style="font-size: 15px; width: 20%" class="text-center" ng-bind="cliente.nit"></td>
                    <td>
                        <button class="btn btn-primary btn-sm" onclick='$("#clientesCat").modal();' id="btnClientesCat">Cambiar</button>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <hr/>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" ng-if='validSale'>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-condensed table-hover" style="margin-bottom: 0px;">
                <tr>
                    <th style="font-size: 21px">Producto</th>
                    <td>
                        Buscar: <input tabindex="1" id="filterProductos" type="text" ng-model="filterProductos"/>
                    </td>
                    <td>
                        <button class='btn btn-warning' onclick='$("#ventaCat").modal()'>
                            Cambiar venta
                        </button>
                    </td>
                </tr>
            </table>
        </div>
        <div class="table-responsive" style="height: 155px; overflow-y: auto">
            <table class="table table-striped table-bordered table-condensed table-hover">
                <tr>
                    <th>Código producto</th>
                    <th>Nombre</th>
                    <th>Marca</th>
                    <th>Tipo / Subtipo</th>
                    <th>Descripción</th>
                    <th>SKU</th>
                    <th>Sucursal</th>
                    <th>Inventario</th>
                    <th>&nbsp;</th>
                </tr>
                <tr ng-repeat="p in productos | filter: filterProductos">
                    <td style="width: 15%;" ng-bind="p.codigo_producto"></td>
                    <td style="width: 15%;" ng-bind="p.nombre"></td>
                    <td style="width: 10%;" ng-bind="p.marca_label"></td>
                    <td style="width: 15%;" >{{p.tipo_label + " - " + p.subtipo_label}}</td>
                    <td style="width: 15%;" ng-bind="p.descripcion"></td>
                    <td style="width: 15%;" ng-bind="p.sku"></td>
                    <td class="be-bold" style="width: 5%; font-size: 15px;" ng-bind="p.stock" ng-class="{'text-success':p.stock>0,'text-danger':p.stock<=0}"></td>
                    <td class="be-bold" style="width: 5%; font-size: 15px;" ng-bind="p.stock_global" ng-class="{'text-success':p.stock_global>0,'text-danger':p.stock_global<=0}"></td>
                    <td style="width: 5%;">
                        <button class="btn btn-success btn-sm" ng-click="addProducto(p)">
                            <span class="glyphicon glyphicon-plus-sign"></span>
                        </button>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <hr/>
    <div class="col-lg- col-md-12 col-sm-12 col-xs-12" ng-if='validSale'>
        <div class="table-responsive" style="margin-top: 25px">
            <table class="table table-striped table-bordered table-condensed" id="productosList">
                <tr colspan="7">
                    <td style="font-size: 15px" class="be-bold">
                        Total venta
                    </td>
                    <td colspan="2" style="font-size: 15px;" ng-class="{'be-bold': totalVentaNormal.selected}">
                        Normal: Q. <span ng-bind="totalVentaNormal.monto"></span>
                    </td>
                    <td colspan="2" style="font-size: 15px;" class="text-warning" ng-class="{'be-bold': totalVentaDocena.selected}">
                        Docena: Q. <span ng-bind="totalVentaDocena.monto"></span>
                    </td>
                    <td colspan="3" style="font-size: 15px;" class="text-success" ng-class="{'be-bold': totalVentaMayorista.selected}">
                        Mayorista: Q. <span ng-bind="totalVentaMayorista.monto" ></span>
                    </td>
                </tr>
                <tr>
                    <th>Código producto</th>
                    <th>Nombre</th>
                    <th>En sucursal</th>
                    <th>Inventario</th>
                    <th>Unidades</th>
                    <th>
                        Precio Unitario 
                        <button ng-show='!editPrecios&&productosSel.length>0' class="btn btn-warning btn-xs" ng-click="editarPrecios()">Editar</button>
                        <button ng-show='editPrecios&&productosSel.length>0' class="btn btn-success btn-xs" ng-click="guardarPrecios()">Guardar</button>
                    </th>
                    <th>Precio Total Producto</th>
                    <th>&nbsp;</th>
                </tr>
                <tr ng-repeat="p in productosSel">
                    <td ng-bind="p.codigo_producto"></td>
                    <td ng-bind="p.nombre"></td>
                    <td ng-bind="p.stock" ng-class="{danger: p.unidades>p.stock}"></td>
                    <td ng-bind="p.stock_global" ng-class="{danger: p.unidades>p.stock_global}"></td>
                    <td>
                        <input type="text" id="{{'unidades_' + p.id_producto}}" tabindex="1" style="width: 50px" ng-model="p.unidades" ng-change="doPrecios()"/>
                    </td>
                    <td>
                        <input type="text" class="modField" ng-model="p.precioFinal" ng-readonly="!editPrecios" ng-change="tienePrecioMod(p)" />
                        <span class="badge badge-info" ng-if="p.precioModificado&&p.precio_tipo=='Especial'">Precio especial</span>
                        <span class="badge badge-info" ng-if="p.precioModificado&&p.precio_tipo=='Docena'">Precio docena</span>
                        <span class="badge badge-info" ng-if="p.precioModificado&&p.precio_tipo=='Unidad'">Precio unidad</span>
                        <span class="badge badge-info" ng-if="p.precioModificado&&p.precio_tipo=='Mayorista'">Precio mayorista</span>
                        <span class="badge badge-success" ng-if="!p.precioModificado&&p.tiene_descuento==1&&p.descuento.id_tipo_descuento==<?php echo Catalogos::DescuentoTipo_Producto ?>">{{ p.descuento.porcentaje_descuento + "% de descuento" }}</span>
                        <span class="badge badge-success" ng-show="!p.precioModificado&&p.tiene_descuento==1&&p.descuento.id_tipo_descuento==<?php echo Catalogos::DescuentoTipo_Marca ?>">{{ "Marca con " + p.descuento.porcentaje_descuento + "% de descuento" }}</span>
                        <span class="badge badge-success" ng-show="!p.precioModificado&&p.tiene_descuento==1&&p.descuento.id_tipo_descuento==<?php echo Catalogos::DescuentoTipo_Tipo ?>">{{ "Tipo de producto con " + p.descuento.porcentaje_descuento + "% de descuento" }}</span>
                        <span class="badge badge-success" ng-show="!p.precioModificado&&p.tiene_descuento==1&&p.descuento.id_tipo_descuento==<?php echo Catalogos::DescuentoTipo_SubTipo ?>">{{ "Subtipo de producto con " + p.descuento.porcentaje_descuento + "% de descuento" }}</span>
                        <span class="badge badge-success" ng-show="!p.precioModificado&&p.tiene_descuento==1&&p.descuento.id_tipo_descuento==<?php echo Catalogos::DescuentoTipo_SegMitadPrecio ?>">2do a mitad de precio</span>
                        <span class="badge badge-success" ng-show="!p.precioModificado&&p.tiene_descuento==1&&p.descuento.id_tipo_descuento==<?php echo Catalogos::DescuentoTipo_DosxUno ?>">2x1</span>
                        <span class="badge badge-success" ng-show="!p.precioModificado&&p.tiene_descuento==1&&p.descuento.id_tipo_descuento==<?php echo Catalogos::DescuentoTipo_3x2 ?>">3x2</span>
                    </td>
                    <td style="font-size: 15px; font-weight: bolder;" ng-bind="(p.precioTotal).toFixed(2)"></td>
                    <td>
                        <button class="btn btn-danger btn-sm" ng-click="quitarProducto(p)">
                            <span class="glyphicon glyphicon-remove-circle"></span>
                        </button>
                    </td>
                </tr>
            </table>
        </div>
        <button class="btn btn-info btn-lg" ng-click="preparePaymentMethod()" ng-show="productosSel.length > 0&&cliente.id_cliente!=''">Forma de pago</button>
        <button class="btn btn-danger btn-lg" ng-click="cancelar()" type="button">Cancelar</button>
    </div>
</div>
