<?php
include CONFIG . "/dbconnection.config.php";
include LIB . "/db.inc.php";
include LIB . "/catalogos.inc.php";
include LIB . "/helpers.inc.php";
include LIB . "/collection.inc.php";
include LIB . "/entity.inc.php";
include LIB . "/productoutil.inc.php";
include LIB . "/empleadoutil.inc.php";
include LIB . "/clienteutil.inc.php";
include LIB . "/phpmailer.inc.php";
include LIB . "/fastmailer.inc.php";
include LIB . "/fastmaintfield.inc.php";
include LIB . "/typeaheadgen.inc.php";
include LIB . "/thumbnailgen.inc.php";
include LIB . "/browser.inc.php";
include LIB . "/fastfield.inc.php";
include LIB . "/filemanager.inc.php";
include LIB . "/angulargridcolumn.inc.php";
include LIB . "/angulargridtemplate.inc.php";
include LIB . "/gridcolumn.inc.php";
include LIB . "/PHPExcel/Classes/PHPExcel.php";
include LIB . "/fastreportcolumn.inc.php";
include LIB . "/pdfmanager.inc.php";
include SYSTEM . "/BaseMod.php";
include SYSTEM . "/AppSecurity.php";
include SYSTEM . "/GeoModError.php";
include SYSTEM . "/GeoAdmin.php";
include WRAPPER . "/BaseWrappedMod.php";
include WRAPPER . "/FastModWrapper.php";
include WRAPPER . "/FastMaintenance.php";
include WRAPPER . "/FastTransaction.php";
include WRAPPER . "/FastReport.php";
include WRAPPER . "/NonDeleteCatalog.php";
include ENT . DS . "MaintenanceTable.php";
include ENT . DS . "ProductoTable.php";
include ENT . DS . "CategoriasModulosTable.php";
include ENT . DS . "ModulosTable.php";
include ENT . DS . "MantModulosTable.php";
include ENT . DS . "PerfilesTable.php";
include ENT . DS . "TipoSiembraTable.php";
include ENT . DS . "ProgramaTable.php";
include ENT . DS . "ActividadTable.php";
include ENT . DS . "AreaTable.php";
include ENT . DS . "UnidadMedidaTable.php";
include ENT . DS . "IngredienteTable.php";
include ENT . DS . "LoteTable.php";
include LIB . "/selecttemplate.inc.php";
include LIB . "/buttontemplate.inc.php";
include LIB . "/Picqer/Barcode/BarcodeGeneratorHTML.php";
